# Generated by Django 5.2 on 2025-04-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('accommodation', 'start_date', 'end_date'), name='unique_reservation_dates'),
        ),
        migrations.AddField(
            model_name='rating',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='basic.accommodation'),
        ),
        migrations.AddField(
            model_name='rating',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='basic.member'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('accommodation', 'member')},
        ),
    ]
