# Generated by Django 4.2 on 2025-04-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_rating_reservation_unique_reservation_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='latitude',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='longitude',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
