# Generated by Django 4.2 on 2025-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_accommodation_latitude_accommodation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_campus',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
