# Generated by Django 4.2 on 2025-04-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_accommodation_distance_to_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='distance_to_campus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
