# Generated by Django 5.2 on 2025-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_accommodation_active_member_active_rating_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['accommodation', 'start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_dates',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='test@amiya.eu.org', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
