# Generated by Django 5.2 on 2025-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_rating_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='distance_to_campus',
            new_name='distance_to_CUHKcampus',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUSTcampus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUcampus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUcampus_kadoorie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUcampus_sassoon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
