# Generated by Django 4.2 on 2025-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_rename_distance_to_campus_accommodation_distance_to_cuhkcampus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUcampus_dentistry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance_to_HKUcampus_swire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='no_of_bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='type_of_accommodation',
            field=models.CharField(default='Single', max_length=50),
            preserve_default=False,
        ),
    ]
