# Generated by Django 4.2 on 2025-04-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='shared_bathroom',
            new_name='Accommodation_invisible',
        ),
    ]
